version: '3'

services:
  container0:
    image: ironlad/pngm_worker:latest
    # ports:
    #   - "49160:3000"
    networks:
      - my-network
  container1:
    image: ironlad/pngm_worker:latest
    # ports:
    #   - "49161:3000"
    networks:
      - my-network
  container2:
    image: ironlad/pngm_worker:latest
    # ports:
    #   - "49162:3000"
    networks:
      - my-network
  container3:
    image: ironlad/pngm_master:latest
    depends_on:
      - container0
      - container1
      - container2
    networks:
      - my-network
networks:
  my-network:
    driver: bridge